AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-crud-backend

  Sample SAM Template for sam-crud-backend

Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
            Variables:
              ddb_table_name: !Ref UserTable
      Events:
        PostUser:
          Type: Api
          Properties:
            Path: /user
            Method: POST
        ReadUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: GET
        UpdateUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: PUT
        DeleteUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: DELETE
        GetAllUsers:
          Type: Api
          Properties:
            Path: /user
            Method: GET

  UserTable:
      Type: AWS::Serverless::SimpleTable
      Properties:
        TableName: UserTable

  LambdaDDBConnector:
      Type: AWS::Serverless::Connector
      Properties:
        Source:
          Id: UserFunction
        Destination:
          Id: UserTable
        Permissions:
          - Write
          - Read

Outputs:
  UserApi:
    Description: "API Gateway endpoint URL for Prod stage for User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user/"

  UserApiDomainName:
    Description: "API Gateway domain name"
    Value: !Sub "${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
